# Generated by Django 2.1.7 on 2019-03-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190305_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default='Misc', max_length=20),
        ),
    ]
