# Generated by Django 2.1.7 on 2019-03-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post1',
            name='tag',
            field=models.CharField(max_length=200),
        ),
    ]
